name: macos ldc build
on: [push, pull_request]

jobs:
  macos-build:
    name: macos dub build
    strategy:
      matrix:
        os: [macos-latest]
        dc: [ldc-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}

      - name: Install htslib deps
        run: |
            brew install xz autoconf automake cython wget
      - name: Get htslib version
        id: get-htslib-version
        run: |
            echo "::set-output name=htslib_version::1.13"

      - name: Cache htslib
        id: cache-htslib
        uses: actions/cache@v2
        with:
          path: htslib-${{ steps.get-htslib-version.outputs.htslib_version }}
          key: ${{ runner.os}}-htslib-${{ steps.get-htslib-version.outputs.htslib_version }}

      - name: Build htslib
        if: steps.cache-htslib.outputs.cache-hit != 'true'
        run: |
            wget https://github.com/samtools/htslib/releases/download/${{ steps.get-htslib-version.outputs.htslib_version }}/htslib-${{ steps.get-htslib-version.outputs.htslib_version }}.tar.bz2
            tar -xf htslib-${{ steps.get-htslib-version.outputs.htslib_version }}.tar.bz2
            cd htslib-${{ steps.get-htslib-version.outputs.htslib_version }}
            ./configure
            make

      - name: Install htslib
        run: |
            cd htslib-${{ steps.get-htslib-version.outputs.htslib_version }}
            sudo make install

      - name: Run tests
        run: dub build -b release
        env:
          LIBRARY_PATH: /usr/local/lib

      - name: fix binary and compress
        run: |
            install_name_tool -change /usr/local/lib/libhts.3.dylib @rpath/libhts.3.dylib nopilesum
            tar -czvf nopilesum.darwin-amd64.tar.gz nopilesum
      
      - name: upload osx artifact
        uses: actions/upload-artifact@v2
        with:
          name: nopilesum-osx
          path: nopilesum.darwin-amd64.tar.gz

  docker-build-and-release:
    name: release with static linux binary
    needs: macos-build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get the tag
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3 | sed 's/^v//')

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push nopilesum image
        id: docker_build_nopilesum
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: charesgregory/nopilesum:latest,charesgregory/nopilesum:${{ steps.get_version.outputs.VERSION }}

      - name: extract nopilesum binary
        uses: shrink/actions-docker-extract@v1
        id: extract
        with:
          image: charesgregory/nopilesum:latest
          path: /home/nopilesum/nopilesum
      
      - name: compress binary
        run: tar -czvf nopilesum.many-linux-x86_64.tar.gz ${{ steps.extract.outputs.destination }}/nopilesum

      - name: Download osx binary
        uses: actions/download-artifact@v2
        with:
          name: nopilesum-osx

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: nopilesum.many-linux-x86_64.tar.gz,nopilesum.darwin-amd64.tar.gz
          generate_release_notes: true
          draft: true

      # - name: Upload coverage
        # run: bash <(curl -s https://codecov.io/bash)